In [26]:
import itertools, operator, os, datetime, csv
import numpy as np
import pandas as pd

doctopic = pd.read_csv("/Users/koitaroh/Documents/GitHub/GeoTweetCollector/data/doctopic_twitter_20150709_21.csv", names = ['topic0','topic1','topic2','topic3','topic4','topic5','topic6','topic7','topic8','topic9','topic10','topic11','topic12','topic13','topic14','topic15','topic16','topic17','topic18','topic19'])
unit_names = pd.read_csv("/Users/koitaroh/Documents/GitHub/GeoTweetCollector/data/docnames_twitter_20150709_21.csv", names = ['sid'])

In [27]:
doctopic[:5]

,topic0,topic1,topic2,topic3,topic4,topic5,topic6,topic7,topic8,topic9,topic10,topic11,topic12,topic13,topic14,topic15,topic16,topic17,topic18,topic19
0,0.067308,0.048077,0.048077,0.048077,0.048077,0.048077,0.048077,0.048077,0.048077,0.048077,0.048077,0.048077,0.048077,0.048077,0.067308,0.048077,0.048077,0.048077,0.048077,0.048077
1,0.046890,0.046890,0.046890,0.046890,0.065883,0.046890,0.046890,0.053063,0.053063,0.046890,0.046890,0.046890,0.046890,0.046890,0.059236,0.065408,0.046890,0.046890,0.046890,0.046890
2,0.048077,0.048077,0.048077,0.048077,0.048077,0.048077,0.067308,0.048077,0.048077,0.048077,0.048077,0.048077,0.048077,0.048077,0.067308,0.048077,0.048077,0.048077,0.048077,0.048077
3,0.046296,0.046296,0.046296,0.046296,0.046296,0.046296,0.046296,0.064815,0.046296,0.046296,0.046296,0.046296,0.046296,0.046296,0.046296,0.083333,0.046296,0.046296,0.064815,0.046296
4,0.047187,0.047187,0.047187,0.047187,0.047187,0.047187,0.047187,0.056446,0.047187,0.047187,0.056802,0.056446,0.066061,0.047187,0.047187,0.047187,0.047187,0.047187,0.056446,0.047187

In [28]:
unit_names[:3]

,sid
0,03465_4343
1,07108_4229
2,07400_4071

In [32]:
doctopic.shape

(83532, 20)

In [34]:
unit_names.shape

(83532, 1)

In [35]:
sdoctopic = pd.concat([unit_names, doctopic], axis=1)

In [37]:
sdoctopic[:5]

,sid,topic0,topic1,topic2,topic3,topic4,topic5,topic6,topic7,topic8,...,topic10,topic11,topic12,topic13,topic14,topic15,topic16,topic17,topic18,topic19
0,03465_4343,0.067308,0.048077,0.048077,0.048077,0.048077,0.048077,0.048077,0.048077,0.048077,...,0.048077,0.048077,0.048077,0.048077,0.067308,0.048077,0.048077,0.048077,0.048077,0.048077
1,07108_4229,0.046890,0.046890,0.046890,0.046890,0.065883,0.046890,0.046890,0.053063,0.053063,...,0.046890,0.046890,0.046890,0.046890,0.059236,0.065408,0.046890,0.046890,0.046890,0.046890
2,07400_4071,0.048077,0.048077,0.048077,0.048077,0.048077,0.048077,0.067308,0.048077,0.048077,...,0.048077,0.048077,0.048077,0.048077,0.067308,0.048077,0.048077,0.048077,0.048077,0.048077
3,09707_3294,0.046296,0.046296,0.046296,0.046296,0.046296,0.046296,0.046296,0.064815,0.046296,...,0.046296,0.046296,0.046296,0.046296,0.046296,0.083333,0.046296,0.046296,0.064815,0.046296
4,10214_1262,0.047187,0.047187,0.047187,0.047187,0.047187,0.047187,0.047187,0.056446,0.047187,...,0.056802,0.056446,0.066061,0.047187,0.047187,0.047187,0.047187,0.047187,0.056446,0.047187

In [ ]:
sdoctopic.to_csv('/Users/koitaroh/Documents/GitHub/GeoTweetCollector/data/sdoctopic_twitter_20150709_21.csv', encoding='utf-8')